name: CI
on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npx pnpm i
    - run: npx pnpm test
      env:
        CI: true

  build-push-deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Fetch repository name
      id: repo
      run: echo "::set-output name=repo::$(echo $GITHUB_REPOSITORY | cut -d'/' -f2 -)"
    - name: Fetch commit hash
      id: hash
      run: echo "::set-output name=hash::$(echo $GITHUB_SHA | head -c7)"
    - name: Fetch current date and time
      id: datetime
      run: echo "::set-output name=datetime::$(date -u +'%Y-%m-%dT%H.%M.%SZ')"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: publictransport/${{steps.repo.outputs.repo}}:v1_${{steps.hash.outputs.hash}}_${{steps.datetime.outputs.datetime}}
        cache-from: type=gha
        cache-to: type=gha,mode=max
